version: '3.1'

services:
  students-bot:
    build: .
    env_file:
      - .env
    volumes: 
      - ./bot/templates:/app/templates
    restart: always
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=student_bot
      - POSTGRES_PASSWORD=student_bot 
      - POSTGRES_DB=student_bot
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT:-5432}:5432